name: trashit
description: Trashit lets you to actively reject negativity, hate, and misinformation from your online space.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  firebase_messaging: ^14.7.10
  firebase_remote_config: ^4.3.8
  firebase_performance: ^0.9.3+8
  firebase_dynamic_links: ^5.4.8
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  flutter_animate: ^4.2.0+1
  page_transition: ^2.1.0
  go_router: ^12.1.3
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  collection: ^1.17.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  intl: ^0.18.1
  timeago: ^3.6.0
  url_launcher: ^6.2.1
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  geolocator: ^10.1.0
  image: ^4.1.3
  mime_type: ^1.0.0
  crypto: ^3.0.3
  convert: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/audios/
    - assets/videos/

  fonts:
    - family: Readex Pro
      fonts:
        - asset: assets/fonts/ReadexPro-Light.ttf
          weight: 300
        - asset: assets/fonts/ReadexPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/ReadexPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/ReadexPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ReadexPro-Bold.ttf
          weight: 700