name: Deploy to Preview
on:
  pull_request:
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Install Flutter'
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.x'
      - name: 'Build Web'
        run: |
          flutter pub get
          flutter build web
      - name: 'Deploy to Firebase'
        uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:deploy --expires 1d
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
