name: Build and Deploy (Flutter Web -> Firebase Hosting)

on:
  push:
    branches: [ main ]

# Avoid concurrent deploys on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Build web (release)
        env:
          OPENAI_PROXY_API_KEY: ${{ secrets.OPENAI_PROXY_API_KEY }}
          OPENAI_PROXY_ENDPOINT: ${{ secrets.OPENAI_PROXY_ENDPOINT }}
        run: |
          flutter build web --release --web-renderer canvaskit \
            --dart-define=OPENAI_PROXY_API_KEY=${{ secrets.OPENAI_PROXY_API_KEY }} \
            --dart-define=OPENAI_PROXY_ENDPOINT=${{ secrets.OPENAI_PROXY_ENDPOINT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Create Firebase service account file
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-service-account.json

      - name: Deploy to Firebase Hosting (hosting only)
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-service-account.json
          firebase deploy --only hosting --project o6hxc54nwwi030f8y17tsfe3qxhlt5 --non-interactive --force