steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Set up Flutter
    uses: subosito/flutter-action@v2
    with:
      channel: stable
      cache: true

  - name: Enable web
    run: flutter config --enable-web

  - name: Flutter version
    run: flutter --version

  - name: Install dependencies
    run: flutter pub get

  - name: Build web
    run: flutter build web --release

  - name: Upload web build artifact
    uses: actions/upload-artifact@v4
    with:
      name: web-build
      path: build/web
