name: Build and Deploy (Flutter Web -> Firebase Hosting)

on:
  push:
    branches: [ main ]
  pull_request:

# Avoid concurrent deploys on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build Flutter Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Build web (release)
        env:
          OPENAI_PROXY_API_KEY: ${{ secrets.OPENAI_PROXY_API_KEY }}
          OPENAI_PROXY_ENDPOINT: ${{ secrets.OPENAI_PROXY_ENDPOINT }}
        run: |
          # Build Flutter Web; firebase.json points hosting.public to build/web
          flutter build web --release --web-renderer canvaskit \
            --dart-define=OPENAI_PROXY_API_KEY=${{ secrets.OPENAI_PROXY_API_KEY }} \
            --dart-define=OPENAI_PROXY_ENDPOINT=${{ secrets.OPENAI_PROXY_ENDPOINT }}

      - name: Upload web build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: build/web
          if-no-files-found: error
          retention-days: 7

  deploy_preview:
    name: Deploy Preview (PR)
    needs: build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download web build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: build/web

      - name: Deploy to Firebase Hosting (preview channel)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: o6hxc54nwwi030f8y17tsfe3qxhlt5

  deploy_live:
    name: Deploy Live (main)
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download web build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: build/web

      - name: Deploy to Firebase Hosting (live)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: o6hxc54nwwi030f8y17tsfe3qxhlt5